# -- Builder Image
FROM golang:1.13-alpine3.10 As Builder

WORKDIR /go/src/github.com/davyj0nes/project
COPY . /go/src/github.com/davyj0nes/project

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -tags netgo --installsuffix netgo -o project main.go

# -- Main Image
FROM alpine:3.10

LABEL MAINTAINER=DavyJ0nes
LABEL OWNER=DavyJ0nes

# add root CA TLS certs
RUN apk --no-cache add ca-certificates

RUN adduser -D -s /bin/sh app

# Copy binary from builder image
COPY --from=Builder /go/src/github.com/iZettle/davyj0nes/project /bin/project
RUN chmod a+x /bin/project

# Ensure not runnning as root user
USER app

CMD ["project"]
